### ISSUE TITLE
Question: How to customize the template?

### ISSUE THREAD

**Issue by WILSLanguageSchool** [letItCurl/minimal_marketing#2]
Hello,

We are trying to create a website based off of this Hugo theme, but we cannot find the correct files to edit the contents of the website, namely the main page (header, etc). Where in the directory structure can we expect to find the files that we should edit with out own information? Any help in this matter would be greatly appreciated. 

Best.
WILS

**Comment by letItCurl** [comment]
https://www.loom.com/share/127bd06a303444a38031f36da2069a06?sid=29e346ae-218d-48d6-b78b-8f376c337290

**Comment by letItCurl** [comment]
https://www.skool.com/nomad-solopreneur-3143/about
